### ISSUE TITLE
NoMethodError in `detect_input_language': undefined method `scan' for nil:NilClass

### ISSUE THREAD

**Issue by eMPee584** [tjbladez/translit#9]
calling translit to process stdin fails after entering some text and pressing ENTER:

    /var/lib/gems/2.1.0/gems/translit-0.1.5/lib/translit.rb:35:in `detect_input_language': undefined method `scan' for nil:NilClass (NoMe
            from /var/lib/gems/2.1.0/gems/translit-0.1.5/lib/translit.rb:8:in `convert!'
            from /var/lib/gems/2.1.0/gems/translit-0.1.5/lib/translit.rb:20:in `convert'
            from /var/lib/gems/2.1.0/gems/translit-0.1.5/bin/translit:14:in `<top (required)>'
            from /usr/local/bin/translit:23:in `load'
            from /usr/local/bin/translit:23:in `<main>'

This is on a debian machine, translit installed via gem install.

**Comment by evgenyantipin** [comment]
I have the same  issue, to fix this just add to Gemfile gem "riot" and bundle again.
